

  #https://classic.gazebosim.org/tutorials?tut=ros_control

   # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  shoulder_sweep_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_sweep_joint
    pid: {p: 1000.0, i: .001, d: 60.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

  shoulder_lift_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 3000.0, i: 100.0, d: 175.0, i_clamp_min: -400.0, i_clamp_max: 400.0}

  elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 2500.0, i: 100.0, d: 100.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

  wrist_pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 900.0, i: 10.0, d: 40.0, i_clamp_min: -400.0, i_clamp_max: 400.0}

  wrist_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_roll_joint
    pid: {p: 900.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

  wrist_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_yaw_joint
    pid: {p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}



  #car--------  


  # gazebo_ros_control:
  #   pid_gains:
  #     left_rear_wheel_joint:
  #       p: 100.0
  #       i: 0.001
  #       d: 1.0
  #     right_rear_wheel_joint:
  #       p: 1.0
  #       i: 0.001
  #       d: 1.0
  #     left_front_wheel_joint:
  #       p: 0.0
  #       i: 0.001
  #       d: 1.0
  #     right_front_wheel_joint:
  #       p: 0.0
  #       i: 0.001
  #       d: 1.0

  #Controller 1
  rear_motor_left: 
    type: velocity_controllers/JointVelocityController
    joint: left_rear_wheel_joint  
    pid : {p: 1000.0 , i: 0.0 , d: 0.0} 
  
  rear_motor_right: 
    type: velocity_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid : {p: 1000 , i: 0.0 , d: 0.0} 
  
  front_motor_left: 
    type: effort_controllers/JointPositionController 
    joint: left_front_wheel_joint  
    pid : {p: 1000.0 , i: 0.0 , d: 0.0} 

  front_motor_right: 
    type: effort_controllers/JointPositionController 
    joint: right_front_wheel_joint  
    pid : {p: 1000.0 , i: 0.0 , d: 0.0} 




  # # Position Controllers ---------------------------------------
  # shoulder_sweep_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: shoulder_sweep_joint
  #   pid: {p: 500.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

  # shoulder_lift_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: shoulder_lift_joint
  #   pid: {p: 500.0, i: 100.0, d: 30.0, i_clamp_min: -400.0, i_clamp_max: 400.0}

  # elbow_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: elbow_joint
  #   pid: {p: 10000.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

  # wrist_pitch_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: wrist_pitch_joint
  #   pid: {p: 200.0, i: 10.0, d: 20.0, i_clamp_min: -400.0, i_clamp_max: 400.0}

  # wrist_roll_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: wrist_roll_joint
  #   pid: {p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

  # wrist_yaw_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: wrist_yaw_joint
  #   pid: {p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}

